spring.application.name=toolsManager
server.port=9090
# ── PRODUÇÃO ──────────────────────────────────────────────
spring.datasource.producao.jdbc-url=jdbc:oracle:thin:@ALFA
spring.datasource.producao.username=${DB_PRODUCAO_USER}
spring.datasource.producao.password=${DB_PRODUCAO_PASS}
spring.datasource.producao.driver-class-name=oracle.jdbc.OracleDriver

# ── DIPAG ─────────────────────────────────────────────────
spring.datasource.dipag.jdbc-url=jdbc:oracle:thin:@DELTA
spring.datasource.dipag.username=${DB_DIPAG_USER}
spring.datasource.dipag.password=${DB_DIPAG_PASS}
spring.datasource.dipag.driver-class-name=oracle.jdbc.OracleDriver

# ── DEV2 ──────────────────────────────────────────────────
spring.datasource.dev2.jdbc-url=jdbc:oracle:thin:@GAMMA
spring.datasource.dev2.username=${DB_DEV2_USER}
spring.datasource.dev2.password=${DB_DEV2_PASS}
spring.datasource.dev2.driver-class-name=oracle.jdbc.OracleDriver

# ── DEV1 ──────────────────────────────────────────────────
spring.datasource.dev1.jdbc-url=jdbc:oracle:thin:@BETA
spring.datasource.dev1.username=c_ergon
spring.datasource.dev1.password=cergfh87
spring.datasource.dev1.driver-class-name=oracle.jdbc.OracleDriver

oracle.session.empresa=1
oracle.session.usuario=edinelson.barro

# ── TNS ADMIN ─────────────────────────────────────────────
oracle.net.tns_admin=C:\Users\05741124135\Documents\01-conexao\TNSNAMES.ORA

logging.level.com.zaxxer.hikari=DEBUG
logging.level.com.zaxxer.hikari.HikariConfig=DEBUG